version: "3"
services:
  my-nodejs-app:
    build: .
    ports:
      - "3000:3000"
    links:
      - my-postgres-container:postgres

  my-postgres-container:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres